[build]

  # Directory of Built Files

  publish = "dist/"

  # Production Build Command

  command = "npm run prod"

  # Directory with the Lambda functions to deploy to AWS

  functions = "Lambda/"

[dev]

  # Development Build Command

  command = "./netlify-dev.sh"

  # Webpack-Dev-Server Port

  targetPort = 3000

  publish = "./dist"
  autoLaunch = true


[[headers]]

  for = "/*"

  [headers.values]

      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "SAMEORIGIN"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "same-origin"

