[build]

  publish = "dist/"

  # Default build command.
  command = "npm run prod"

  # Directory with the Lambda functions to deploy to AWS.
  functions = "Lambda/"

[[redirects]]

  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]

  for = "/*"

  [headers.values]
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-XSS-Protection: 1; mode=block
      Feature-Policy: autoplay 'none'; camera 'none'; geolocation 'self'
      Referrer-Policy: same-origin
